require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - lib/generators/active_job/trackable2/templates/*
    - test/dummy/bin/*
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - git_source

Style/MultilineTernaryOperator:
  Enabled: false
