AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - lib/generators/active_job/trackable/templates/*
    - test/dummy/bin/*
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - git_source
